# Site
name: "Covert Channel"
description: "The Art and Science of Covert Communication Channels and Steganography"
meta_description: "Covert Channels, Steganography, Data Hiding, Information Hiding."
logo: assets/images/logo.png
favicon: favicon.ico
baseurl: /
google_analytics: 
disqus: 
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: x
    display_name: x
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: x@gmail.com
    web: https://www.x.net
    twitter: https://twitter.com/x
    description: "Author of  blah blah."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
