# Site
name: "Covert Channel"
description: "The Art and Science of Covert Communications"
meta_description: "Covert Channels, Covert Communications, Steganography, Data Hiding, Information Hiding."
logo: assets/images/logo.png
favicon: favicon.png
baseurl: /
google_analytics: UA-134495322-1
disqus: covert-channel
mailchimp-list: 
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  dlerch:
    name: Daniel Lerch
    display_name: Daniel Lerch
    gravatar: 1b647b431c864b13c659830bf5ce4b00
    email: dlerch@gmail.com
    web: https://www.daniellerch.me
    twitter: https://twitter.com/daniel_lerch
    description: "Author of  blah blah."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge
